max_mem: 240G
min_mem: 5G
salmon_mem: 32G
max_time: 20-00:00:00
min_cpus: 1
max_cpus:  72
fastp_cpus: 24
salmon_cpus: 18
salmon_Gibbs_samples: 100
min_filt_samples: 1
min_filt_counts: 10
phred_score: 20
