"""folders.py: file to store paths to folfers"""
download = "data/download"
reads_fq = "data/reads_fq"
reads_trimmed = "results/trimmed"
STAR_index_dir = "results/extended/STAR_index"
TRANSDECODER_dir = "results/extended/tr_2_prot/merged_reference.transcripts.fasta.transdecoder_dir"
tr_2_prot_dir = "results/extended/tr_2_prot"
